### ISSUE TITLE
Deprecated message on Symfony `6.3`

### ISSUE THREAD

**Issue by misaert** [bpolaszek/doctrine-safe-events#2]
Hi Ben :wave: 

With Symfony `6.3`, I have this deprecated message:

> Since symfony/doctrine-bridge 6.3: Registering "Bentools\DoctrineSafeEvents\SafeEventsDispatcher" as a Doctrine subscriber is deprecated. Register it as a listener instead, using e.g. the #[AsDoctrineListener] attribute.

See https://github.com/doctrine/DoctrineBundle/pull/1664.

`AsDoctrineListener` is provided by `doctrine/doctrine-bundle` but it is not required in this repository.

On the `README`, is is explained to add the following configuration on a Symfony project:
```yaml
Bentools\DoctrineSafeEvents\SafeEventsDispatcher:
    tags:
        - { name: 'doctrine.event_subscriber' }
        - { name: 'kernel.reset', method: 'reset' }
```

What is the best way to fix this?

Thanks,

Mickaël

**Comment by bpolaszek** [comment]
Hey @misaert ! 👋 

I wasn't aware of that deprecation, I actually don't understand why it's deprecated...
Anyway, I think this could easily be changed into:

```yaml
Bentools\DoctrineSafeEvents\SafeEventsDispatcher:
    tags:
        - 
          name: doctrine.event_listener
          event: postPersist
        - 
          name: doctrine.event_listener
          event: postUpdate
        - 
          name: doctrine.event_listener
          event: postRemove
        - 
          name: doctrine.event_listener
          event: postFlush
        - 
          name: kernel.reset
          method: reset
```

Seems a little verbose, but can you give it a try?
Otherwise, making `doctrine/doctrine-bundle` a requirement and use annotations could be an option.
